language: csharp
sudo: true
mono: none
dotnet: 2.1.300
skip_cleanup: true
before_install:
  - nvm install 8
  - nvm use 8
  - cd ./Covalence.Tests/
install:
  - dotnet restore
script:
  - dotnet test
  - cd ../Covalence/
  - dotnet publish -c Release
after_success:
  - cd ../
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=$DOCKER_USER/covalence
  - export TAG=$TRAVIS_BUILD_NUMBER
  - docker build -t $REPO:$TAG .
  - docker tag $REPO:$TAG $REPO:latest
  - docker push $REPO

