language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.1
skip_cleanup: true
before_install:
  - nvm install 8
  - nvm use 8
  - cd ./Covalence.Tests/
install:
  - dotnet restore
script:
  - dotnet test
  - cd ../Covalence/
  - dotnet publish -c Release
after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export COMMIT=$TRAVIS_COMMIT::8
  - export REPO=timdturner/covalence
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS-BUILD-NUMBER
  - docker push $REPO

