version: '3'

services:
  web:
    container_name: 'covalence'
    image: 'covalence'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - postgres
    networks:
      - covalence-network

  postgres:
    container_name: 'postgres'
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - covalence-network

networks:
  covalence-network:
    driver: bridge