version: 2
jobs:
  build: 
    working_directory: ~/Covalence/Covalence
    docker:
      - image: microsoft/aspnetcore-build:1.1
    steps:
      - checkout
      - run:
          name: "Run Tests"
          command: |
            cd ../Covalence.Tests/
            dotnet restore
            dotnet test
      - run:
          name: "Publish"
          command: |
            cd ../Covalence/
            npm i
            dotnet publish -c Release
            