version: 2
jobs:
  build: 
    working_directory: ~/Covalence
    docker:
      - image: microsoft/aspnetcore-build:1.1
    steps:
      - checkout
      - run:
          name: "Run Tests"
          command: |
            cd ./Covalence.Tests/
            dotnet restore
            dotnet test
      - run:
          name: "Publish"
          command: |
            cd ..
            cd ./Covalence
            ls
            npm i
            dotnet publish -c Release
            