version: 2
jobs:
  build: 
    working_directory: ~/
    docker:
      - image: microsoft/aspnetcore-build:1.1
    steps:
      - checkout
      - run: ls
      - run:
          name: Run Tests
          command: |
            cd ../Covalence.Tests
            dotnet restore
            dotnet test