version: 2
jobs:
  build: 
    working_directory: ~/Covalence
    docker:
      - image: microsoft/aspnetcore-build:1.1
    steps:
      - checkout
      - run:
          name: "Run Tests"
          command: |
            cd ./Covalence.Tests/
            dotnet restore
            dotnet test
      - run:
          name: "Publish"
          command: |
            cd ..
            cd ./Covalence/
            dotnet publish -c Release
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build and Publish runtime Docker Container
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t timdturner/covalence:$TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push timdturner/covalence:$TAG