version: 2
jobs:
  build: 
    working_directory: ~/Covalence
    docker:
      - image: microsoft/aspnetcore-build:1.1
    steps:
      - checkout
      - run:
          name: "Go into app folder"
          command: |
            cd Covalence/
            dotnet restore
            dotnet build
#  test:
#    working_directory: ~/Covalence/Covalence.Tests
#    steps:
#      - run:
#          name: Run Tests
#          command: |
#            dotnet restore
#            dotnet test
#  deploy_production:
#    working_directory: ~/
#    docker:
#      - image: microsoft/aspnetcore-build:1.1
#    steps: